Meeting.md
=> Meeting minutes for 3/30 and 4/6/2022

README.md, sw_firewall/README.md
Factor the initial sw firewall PoC info to its own file
=> Add new intro README

Meeting.md
=> Meeting minutes 4/20/2022

sw_firewall/README.md, sw_firewall/conf/nginx/index.html, sw_firewall/docker-compose.yml
This commit modifies the README.md to show how to setup the PoC
environment dependencies (Docker, Docker compose, IPDK, and
ipdk-plugin). It also adds a docker-compose.yml file for the demo
itself.
=> PoC: First cut at PoC setup

.github/workflows/poc.yml, sw_firewall/Makefile, sw_firewall/scripts/poc.sh, sw_firewall/scripts/run-shellcheck.sh
Enable Github Actions on the PoC repo to setup and run the PoC on pull
requests and merges.
=> actions: Enable GitHub Actions

.github/workflows/poc.yml, sw_firewall/scripts/poc.sh
=> Fix shellcheck job

README.md
=> Add GitHub Actions status badge to README.md

sw_firewall/README.md
This commit updates the README.md file to reflect the reality of the
initial PoC work being done using containers and IPDK P4-eBPF.
=> README.md: Update language around PoC

Meeting.md
=> Meeting minutes for 5/4/2022

README.md
This PR replaces https://github.com/opiproject/opi-poc/pull/4
=> Added Contribute section.

networking/README.md
=> Fix wording in PoC README.md

storage/Dockerfile.spdk, storage/README.md, storage/docker-compose.yml
=> storage: first commit

Meeting.md
=> Meeting minutes for June 2022 meetings

.github/dependabot.yml, .github/workflows/markdown.yml, Meeting.md, README.md, integration/host-bmc/README.md, integration/host-cpu/README.md, integration/pxe/README.md, integration/spdk/README.md, integration/telegraf/README.md, integration/xpu-bmc/README.md, networking/README.md, storage/README.md
This adds both markdown linting and the dependabot to keep our GitHub
Actions up to date.
=> CI: Add markdown lint and dependabot

.github/dependabot.yml
=> depen: make sure dockerfiles are up2date

.github/workflows/poc-networking-skip.yml, .github/workflows/poc-storage-skip.yml
Skip jobs should not cancel non-skip jobs.
=> CI: Fix grouping for CI jobs

networking/README.md
Also, test merges to main to see if the issues #37 was trying to fix are
resolved.
=> README.md: Update wording

integration/pxe/README.md, integration/telegraf/README.md, integration/telegraf/telegraf-redfish.conf
=> integration: update PXE readme and Fix redfish Telegraf plugin

integration/README.md
=> integration: readme howto run

README.md
=> Integration test status badge

integration/README.md, integration/docker-compose.yml, integration/host-cpu/Dockerfile, integration/host-cpu/README.md, integration/xpu-cpu/Dockerfile, integration/xpu-cpu/README.md
Things that run on the same BOX need to have same network
=> integration: use same network where matters

.github/workflows/poc-integration.yml, integration/README.md, integration/docker-compose.dpu.yml
- integration: use same network where matters
- split compose to host and dpu
=> split compose to host and dpu

integration/docker-compose.dpu.yml, integration/docker-compose.pxe.yml, integration/docker-compose.spdk.yml, integration/xpu-cpu/telegraf-redfish.conf
=> Add SPDK target container Fixes #68

integration/README.md, integration/scripts/integration.sh
=> ci: add SPDK to CI

integration/scripts/integration.sh
=> ci: tests always pass

integration/docker-compose.xpu.yml, integration/docker-compose.yml
=> add more healthcheck for ssh

integration/docker-compose.spdk.yml, integration/docker-compose.xpu.yml, integration/scripts/integration.sh
=> integration: fix spdk

integration/docker-compose.spdk.yml, integration/scripts/integration.sh
=> ci: add more test for SPDK (identify)

integration/scripts/integration.sh
=> integration: fix logs print

integration/scripts/integration.sh
=> build: make it faster by paralleleizing

integration/docker-compose.pxe.yml, integration/pxe/Dockerfile, integration/pxe/Dockerfile.sztp
=> sztp: Fixes #78

integration/pxe/Dockerfile, integration/scripts/integration.sh
Makes debugging #85 easier.
Related to Isse #85
=> pxe: Add nmap to pxe container

integration/docker-compose.spdk.yml, integration/docker-compose.xpu.yml, integration/scripts/integration.sh
=> ci: add more tests for nvme spdk perf

integration/.env, integration/scripts/integration.sh
=> introduce .env

.github/workflows/markdown.yml, integration/host-cpu/Dockerfile, integration/pxe/Dockerfile, integration/pxe/README.md, integration/spdk/Dockerfile, storage/Dockerfile
=> CI: add docekrfile hadolint

integration/docker-compose.spdk.yml, integration/docker-compose.xpu.yml, integration/scripts/integration.sh
=> ci: break loop on success

.github/workflows/poc-integration.yml, integration/README.md, integration/scripts/integration.sh
=> ci: small renaming of run-test

integration/pxe/Dockerfile.sztp, integration/scripts/integration.sh
=> ci: test sztp

integration/docker-compose.spdk.yml, integration/docker-compose.xpu.yml
=> spdk: no PCIe

Meeting.md
=> Meeting minutes for 7/13/2022

integration/docker-compose.spdk.yml
=> fix spdk health

README.md
=> Update README.md with all PoCs

.github/workflows/poc-integration.yml
=> Add huge pages allocation checker step

.github/workflows/poc-storage.yml, storage/docker-compose.yml
- move SPDK docker to storage
- ci: storage: publish SPDK container to ghcr
=> ci: storage: publish SPDK container to ghcr

storage/Dockerfile
=> add healthcheck to spdk dockerfile

.github/workflows/poc-integration.yml, integration/docker-compose.spdk.yml, integration/docker-compose.xpu.yml
=> user pre-built storage image

storage/Dockerfile
=> storage: add cmd and port to dockerfile

integration/docker-compose.xpu.yml, integration/scripts/deploy.sh, integration/scripts/integration.sh, integration/xpu-cpu/Dockerfile.telegraf
=> deploy: working on real hw remote xPU

.github/workflows/poc-storage.yml, storage/Dockerfile
Reverts opiproject/opi-poc#164
=> Revert "spdk: Use native arch and skip AVX"

integration/README.md, integration/docker-compose.otel.yml, integration/docker-compose.pxe.yml, integration/docker-compose.xpu.yml, integration/otel/README.md, integration/scripts/integration.sh
=> Initial support for running on Fedora

integration/docker-compose.pxe.yml, integration/scripts/integration.sh
=> tests: fix tftp always return 0

integration/gateway/Dockerfile.network, integration/gateway/Dockerfile.storage, integration/scripts/integration.sh
- gateway: enable tests fro example clients
- gateway: reduce network service docker image size
- gateway: reduce storage service docker image size
=> gateway: reduce network and storage docker image sizes

integration/README.md
=> doc: docker-compose version

.github/workflows/markdown.yml, .github/workflows/poc-integration.yml, .github/workflows/poc-networking.yml, .github/workflows/poc-storage.yml
=> CI: add workflow_dispatch for manual triger

integration/docker-compose.xpu.yml
=> storage: split xpu spdk container

.github/workflows/poc-storage.yml, storage/scripts/poc.sh
=> ci: enhance storage tests

storage/docker-compose.yml, storage/scripts/poc.sh
=> ci: storage POC

storage/README.md, storage/docker-compose.yml, storage/scripts/poc.sh
=> storage: add compose and test

storage/README.md, storage/docker-compose.yml, storage/server.go
=> storage: add unix socker for spdk

storage/README.md, storage/client.go, storage/docker-compose.yml, storage/go.mod, storage/go.sum, storage/server.go
also don't use `host` networking
=> storage: update to latest proto

storage/README.md, storage/docker-compose.yml, storage/jsonrpc.go, storage/server.go
=> storage: just move spdk to a separate file

storage/Dockerfile, storage/Makefile, storage/README.md, storage/backend.go, storage/client.go, storage/docker-compose.yml, storage/frontend.go, storage/jsonrpc.go, storage/middleend.go, storage/server.go
=> storage: move fe,be to a separate file

storage/client.go, storage/frontend.go
=> storage: add more proto

storage/docker-compose.yml
=> storage: remove port export since we on the same network

storage/server/frontend.go, storage/server/jsonrpc.go, storage/server/server.go
=> storage: replace strings with structs for json

storage/client/client.go, storage/go.mod, storage/go.sum, storage/server/backend.go
=> storage: implement more backend funcs

storage/README.md, storage/client/backend.go, storage/client/client.go, storage/client/frontend.go, storage/client/middleend.go, storage/docker-compose.yml
=> storage: split client into files

integration/docker-compose.otel.yml, integration/docker-compose.pxe.yml
* Force ipv4 only on in.tftpd
* SELinux for otel-gw-collector
See commits for details
=> Rhel86 host support

integration/scripts/integration.sh
Closes #232
Use query that is compatible with both docker and podman to check
example client test results.
=> Support client tests with podman

storage/client/backend.go, storage/client/frontend.go, storage/go.mod, storage/go.sum, storage/server/backend.go, storage/server/frontend.go, storage/server/jsonrpc.go
=> storage: parse spdk correctly

storage/client/backend.go, storage/client/frontend.go, storage/go.mod, storage/go.sum, storage/server/backend.go, storage/server/frontend.go
=> storage: fix proto after linters

storage/client/frontend.go, storage/server/frontend.go
- vhost_create_blk_controller
- vhost_delete_controller
- vhost_get_controllers
=> storage: use real vhost commands

.github/workflows/poc-storage.yml
=> ci: avoid second build, pass sha

.github/workflows/poc-storage.yml
=> ci: use docker cache to speed up build

.github/workflows/linters.yml, security/server/ipsec_messages.go
=> ci: add go linter for security

security/client/Dockerfile, security/server/Dockerfile
=> security: add server and client dockerfiles

storage/client/frontend.go, storage/docker-compose.yml
=> storage: reorder Virtio tests

.github/workflows/poc-security.yml
=> security: add small test

storage/scripts/poc.sh
=> storage: fixing exit code

.github/workflows/poc-security-skip.yml, .github/workflows/poc-security.yml
=> security: push go-docker images

security/docker-compose.yml, storage/docker-compose.yml
=> storage: security: use pre-built images

storage/client/frontend.go, storage/server/frontend.go
=> storage: fix device naming

storage/README.md
=> storage: add grpc-cli to readme

security/README.md
=> securtity: update readme

.github/dependabot.yml
=> dependabot: add go dependencies

.github/workflows/poc-integration.yml, .github/workflows/poc-storage.yml, integration/docker-compose.spdk.yml, integration/docker-compose.xpu.yml, storage/docker-compose.yml
=> storage: add hugetls mount

storage/README.md
=> readme: document huge pages

.github/workflows/poc-security-skip.yml, .github/workflows/poc-storage-skip.yml
=> ci: fixing skip ci

.github/workflows/poc-security.yml, integration/scripts/integration.sh, storage/scripts/poc.sh
=> ci: check reflection

security/server/ipsec.go
This implements the IPsecGet() API by fetching resulting data from Redis
based on the uuid passed i.
=> security: Implement IPsecGet()

.github/workflows/poc-security.yml, storage/scripts/poc.sh
=> grpc_cli: check more reflection

storage/README.md, storage/qemu_spdk_setup.md
=> storage: add qemu documentation

storage/qemu_spdk_setup.md
=> storage: add qemu HOTPLUG documentation

Meeting.md
=> Meeting minutes: Aug 10, 2022

storage/qemu_spdk_setup.md
=> storage: add qemu virtio-scsi doc

integration/docker-compose.pxe.yml, integration/gateway/Dockerfile.network, integration/host-cpu/Dockerfile, integration/host-cpu/Dockerfile.telegraf, integration/pxe/Dockerfile, integration/pxe/Dockerfile.dhcp, integration/pxe/Dockerfile.sztp, integration/pxe/Dockerfile.tftp, integration/pxe/README.md, integration/scripts/integration.sh, integration/xpu-cpu/Dockerfile, security/client/Dockerfile, security/server/Dockerfile, storage/spdk/Dockerfile
- pxe: use nmap image
- pxe: cplit dhcp and tftp
- align to dockerhub registry
- small fix
=> pxe: split dhcp and tftp

integration/pxe/README.md, integration/pxe/dhcpd.conf.template
=> dhcp: add cutom options

security/server/ipsec.go, security/server/ipsec_vici.go
This adds connection deletion support.
Related to #220
=> security: Flesh out delete operations

.gitignore, setup/README.md, setup/redhat/setup.yml, setup/ubuntu/setup.yml
This contains ansible playbooks for doing basic setup for running
the simulation/test environments.  These can certainly be extended.
=> Simple playbooks for automating setup

integration/docker-compose.pxe.yml, integration/pxe/Dockerfile.sztp
=> sztpd: allow external access

.github/workflows/poc-security.yml
=> ci: add more security reflection

security/client/client.go, security/client/ipsec.go, security/server/ipsec_vici.go
This fleshes out the rest of the vici backend for loading connections
into strongSwan. Along the way, I've built a helper function
(buildProposal()), which is used to build proposals in a generic way.
Related to #220
=> security: Finish fleshing out connect

security/client/ipsec.go, security/server/ipsec.go, security/server/ipsec_vici.go
This implements the IPsecStats() API, and adds support to the gRPC
client to test it out.
Related to #320
=> security: Implement IPsecStats API

.github/workflows/poc-security.yml, security/client/ipsec.go, security/server/ipsec.go, security/server/ipsec_vici.go
This commits implements the IPsecRekey() API.
Related to #320
=> security: Implement IPsecRekey API

security/client/go.mod, security/client/go.sum, security/server/go.mod, security/server/go.sum, security/server/ipsec_vici.go
This moves child_id and ike_id to uint64.
Closes #336
=> security: Change child_id and ike_id to uint64

integration/otel/prometheus.yaml
I'm able to reproduce the issue and able to see metrics with the fix. 
Please review it. Thanks.
=>   Fix for issue: #185

integration/scripts/integration.sh
=> integration: better handle compose plugin

integration/docker-compose.xpu.yml, integration/scripts/integration.sh
=> ci: add prometheus query tests

security/client/go.mod, security/client/go.sum, security/server/go.mod, security/server/go.sum, security/server/server.go, security/server/sessionoffload.go
This is an initial attempt to realize the new OPI Security session offload APIs [1].
Related to #355
[1] https://github.com/opiproject/opi-api/blob/main/security/proto/openoffload.proto
=> security: First attempt at offload API

.github/workflows/poc-security.yml
This adds basic SessionTable CI
Related to #355
=> security: Add CI for SessionTable

storage/scripts/poc.sh
Signed-off-by: Alan White <alan.w@dell.com>
=> Issue #360 validate arg count

integration/gateway/Dockerfile.network
=> grpc: update version

integration/docker-compose.host.yml, integration/docker-compose.xpu.yml, storage/README.md
=> storage: improve/fix documentation

storage/README.md
=> storage: show real HW example

storage/README.md
=> storage: one more example

storage/client/backend.go, storage/docker-compose.yml, storage/server/backend.go
=> storage: implement bdev_nvme_attach_controller

storage/server/backend.go
=> storage: return value fix from spdk

storage/server/backend.go, storage/server/frontend.go, storage/server/spdk.go
=> storage: refactor spdk structs to a separate file

.gitignore, security/client/go.mod, security/server/go.mod, storage/client/go.mod, storage/server/go.mod
Update go version to 1.19 in go.mod files
Add intellij config files to .gitignore
Signed-off-by: patrick-alessi <patrick.alessi@dell.com>
=> Update go version to 1.19 in go.mod files

storage/server/frontend.go, storage/server/jsonrpc.go, storage/server/spdk.go
- storage: spdk log fix
- storage: more refactoring
=> storage: spdk log fix and more refactoring

security/README.md, storage/README.md
=> readme: fix after renaming

setup/README.md
=> Clarify ansible inventory file

setup/redhat/setup.yml, setup/ubuntu/setup.yml
=> ansible: configure huge pages

storage/scripts/poc.sh
=> storage: better handle compose plugin

.github/workflows/linters.yml, networking/docker-compose.yml, security/docker-compose.yml, storage/docker-compose.yml
=> ci: more YAMLlint

setup/redhat.yml
=> Ensure pip3 is installed for Red Hat

integration/docker-compose.pxe.yml
=> docker: use full path

storage/scripts/poc.sh
Calling docker-compose run or up inside the tests is problematic, with intermittent failures on docker and persistent failures on podman. Instead, have the tests check the status of the existing client container.
=> storage: remove redundant client call

storage/client/backend.go, storage/client/go.mod, storage/client/go.sum, storage/server/backend.go, storage/server/go.mod, storage/server/go.sum
Update client and server to pass AioController filename
=> Update client and server to pass AioController filename

.golangci.yml, storage/client/backend.go, storage/client/client.go, storage/client/frontend.go, storage/client/go.sum, storage/client/middleend.go, storage/server/backend.go, storage/server/jsonrpc.go, storage/server/spdk.go
I added a bunch of linters via [golangci-lint](https://github.com/golangci/golangci-lint) and then fixed the issues raised by the linters.
=> Clean up POC code

storage/README.md, storage/docker-compose.yml
- storage: make sure /var/tmp is used for virtio sockets
- storage: reduce healthcheck output
- storage: share /var/tmp with host to use virtio initiator
- storage: improve readme
=> storage: make sure /var/tmp is used for virtio sockets

storage/server/frontend.go
=> storage: fix empty list reponse

storage/client/frontend.go, storage/server/frontend.go, storage/server/spdk.go
=> storage: change frontend nvme-ns to nvmf_subsystem_add_ns

storage/qemu_spdk_setup.md
=> qemu: add doc for vfio-user

storage/client/backend.go, storage/docker-compose.yml, storage/spdk/Dockerfile
127.0.0.1 didn't allow us to connect
=> spdk: allow external connectivity

storage/client/frontend.go, storage/server/frontend.go, storage/server/spdk.go
=> storage: change frontend nvme-subsys to nvmf_create_subsystem

storage/README.md
=> storage: simplify readme

storage/client/frontend.go, storage/server/frontend.go, storage/server/spdk.go
=> storage: add NVMeNamespaceList

storage/client/frontend.go, storage/server/frontend.go
=> storage: add NVMeNamespaceGet

integration/docker-compose.spdk.yml, integration/docker-compose.xpu.yml
=> storage: remove context and use published images only

integration/README.md
Replace prereqs section with link to Ansible section
=> integration: cleanup README prereqs

integration/docker-compose.pxe.yml, integration/scripts/integration.sh
=> sztp: align to sztp repo docker-compose

integration/docker-compose.pxe.yml
=> sztp: expand command line

.github/workflows/poc-security.yml
=> security: ci: always collect logs

integration/docker-compose.xpu.yml
=> strongswan: add healthcheck

README.md
see https://github.com/opiproject/opi-spdk-bridge
Signed-off-by: Boris Glimcher <36732377+glimchb@users.noreply.github.com>
=> Removing old storage badge

integration/docker-compose.spdk.yml, integration/docker-compose.xpu.yml
See opiproject/opi-spdk-bridge#51
=> SPDK image rename

integration/docker-compose.pxe.yml
=> opi-sztp-server now requires SZTPD_OPI_MODE be set

integration/docker-compose.pxe.yml, integration/docker-compose.spdk.yml, integration/docker-compose.xpu.yml
=> [docker] pull images by digest instead of labels

setup/setup.yml
=> Fix setup.yml indentation

integration/docker-compose.pxe.yml, integration/scripts/integration.sh
=> enable sztp test failure

renovate.json
the images co-depend, so need to update them at once
=> renovate: group sztp images together

renovate.json
Signed-off-by: Boris Glimcher <36732377+glimchb@users.noreply.github.com>
=> renovate: try automerge for digests only

integration/scripts/integration.sh
The failure rate due to #630 is quite high. In the meantime, this works around it keeping the CI running until a proper fix can be found.
=> integration: workaround for intermittent CI failures

integration/docker-compose.pxe.yml, integration/scripts/integration.sh, integration/sztp/dhcpd.conf.template
=> Replace opi-dhcp-server with networkboot/dhcpd

integration/docker-compose.pxe.yml, integration/sztp/dhclient.conf
=> Replace opi-dhcp-client with modularitycontainers

lab/bom.md
Signed-off-by: Paul Pindell <ppindell@gmail.com>
=> Update Bom.md with additional selection criteria

integration/gateway/Dockerfile.network
=> bump route_guide grpc version

.github/renovate.json, integration/gateway/Dockerfile.network
=> renovate: update custom docker file

demos/security/marvell/README.md
This demo shows Strongswan off-chip configuration using opi- strongswan-bridge.
=> docs: strongswan integration into marvell dpu

demos/storage/README.md, demos/storage/intel/README.md, demos/storage/nvidia/README.md
=> docs(demo): add intel storage demo video link

integration/scripts/integration.sh
This reverts commit a279c4375e2fee715f23a05c96f05dda3a8004c8.
=> Revert "stats: rename net_bytes_recv"

lab/hardware/ips.md
docs: Update IPs.md add F5 BIG-IP VPN IPs
Signed-off-by: Paul Pindell <ppindell@gmail.com>
=> docs: update ips.md

lab/README.md
Signed-off-by: Paul Pindell <ppindell@gmail.com>
=> Doc: Update README.md

lab/ips.md
- dh4
- intel dyp
- marvell bmc
=> adds ipu host 4 ips

lab/hardware/dh4/README.md
creates IPU Host 4 readme file
=> IPU Host 4 readme file

.github/workflows/opi-lab.yml, demos/tgen/test_tgen_demo.py
- removes need for root password
- fix for missing env file
- moves path into a variable, but ultimately should be removed completely in a subsequent PR
=> removes need for root password

lab/ansible/setup.yml
=> fix(ansible): refactor intelmev play using delegate

lab/hardware/mgmt/fs/etc/dhcp/dhcpd.conf, lab/server-setup.md
adds dhcp server config on mgmt server
=> dhcp server config and instructions
