.github/workflows/poc-networking-skip.yml, .github/workflows/poc-networking.yml, .github/workflows/poc-storage-skip.yml, .github/workflows/poc-storage.yml
This moves networking and storage CI into separate jobs. It also
conditionally runs them only if you modified things in the respective
networking or storage directories.
=> CI: Refactor CI

.github/dependabot.yml
https://github.com/dependabot/dependabot-core/issues/2178
=> why dependabotdoesn't support glob?

integration/docker-compose.pxe.yml, integration/docker-compose.spdk.yml, integration/docker-compose.telegraf.yml, integration/docker-compose.yml, integration/pxe/Dockerfile
This changes the subnet definitions for the PXE setup, and also moves to
define the docker network in one docker compose file and then use it in
the other ones.
=> integration: Get PXE working

integration/docker-compose.pxe.yml, integration/docker-compose.telegraf.yml, integration/docker-compose.yml
This commit fixes the integration docker compose setup to get the
networking correct. A few items were address:
* Change subnet to 10.127.127.0/24
* Use separate host port mappings for the multiple ssh servers
* Add a name to the opi network
With this change, things come up smoothly:
```
vagrant@bullseye:/git/opi-poc/integration$ docker compose -f docker-compose.yml -f docker-compose.telegraf.yml -f docker-compose.pxe.yml up -d
[+] Running 8/8
⠿ Network opi                       Created                                                                                                                                                                        0.0s
⠿ Container integration-host-cpu-1  Started …
```
=> integration: Fix networking

integration/README.md, integration/scripts/integration.sh
This modifies the README.md to reflect the fact we can use the actual
integration tests run in the CI for developer usage as well.
Further, it modifies the integration.sh script to handle various version
of `docker compose`, including how it is installed.
=> integration: Use script for examples

.github/workflows/poc-integration.yml, integration/README.md, integration/scripts/integration.sh
Commit d2c2f91 made a separate build argument to the integration script,
but left build-start. This commit makes the split between build and
start much more clear by decoupling them completely and requiring each
to be called to run the integration tests.
=> integration: Really separate build and start

integration/scripts/integration.sh
it was added to find the DHCP issue and doesn't provide a lot of value
and it crashes now with new DC syntax changes, so removing it.
=> integration: remove inspect command

integration/docker-compose.spdk.yml, integration/docker-compose.xpu.yml, integration/scripts/integration.sh, integration/spdk/Dockerfile
Move to a multi-stage build for the SPDK container to "contain" it's
size. You can see the shrinking that happens once we do this below:
```
vagrant@bullseye:~$ docker images|grep spdk
integration_xpu-spdk                          latest         c3628be1417d   6 minutes ago    219MB
integration_spdk-target                       latest         c3628be1417d   6 minutes ago    219MB
integration_ipu-spdk                          latest         71e23aabe2f3   12 days ago      1.24GB
integration_spdk                              latest         71e23aabe2f3   12 days ago      1.24GB
```
Closes #115
=> spdk: Use multi-stage Docker build

integration/docker-compose.xpu.yml, integration/scripts/integration.sh
This updates the Kong configuation to listen on https as well as http
ports. It adds some simple API tests to verify the API endpoints are up
and running as well.
Closes #120
=> tests: Add Kong tests

integration/scripts/deploy.sh
This adds a deployment script to allow deploying the OPI PoC on either
the developer emulated environment, or in a split xPU /
[host,VM,container] environment.
Fixes #133
=> deploy: Add deployment script

storage/Dockerfile
We can't use `native` as the ARCH for SPDK builds because the Azure
Runners which GitHub Actions uses container CPUs with those
instructions. Instead, force the ARCH to `x86_64` so the build wil
disable those instructions [1].
Closes #159 
[1] https://github.com/spdk/spdk/blob/master/mk/spdk.common.mk#L73-L78
=> SPDK: Build without AVX instructions

.github/workflows/poc-storage.yml, storage/Dockerfile
This moves back to native arch for the SPDK container, but removes AVX
using CFLAGS instead.
Note that this may not work on ARM, and we may need to conditionally
remove AVX only for x86_64 targets.
Related #160
=> spdk: Use native arch and skip AVX

integration/docker-compose.host.yml, integration/scripts/deploy.sh
Host  - where xPU is plugged into (default is my laptop)
XPU   - obvious, arm64 cores (default is my laptop)
Infra - where DHCP, PXE, TFTP, OTEL, ... live (default is my laptop)
This might help:
```
ssh-copy-id <user>@<remote-ip>
```
=> deploy: add option to deploy to anotehr host as well

integration/docker-compose.host.yml, integration/host-cpu/Dockerfile.telegraf, integration/host-cpu/telegraf-redfish.conf
like agent on xPU it is another agent on host
both agents send data to otel collector gw
=> telegraf: add another agent to host

storage/Dockerfile
Building spdk image on Arm failed with "pip3 not found".
=> spdk: Fix spdk docker image build error on Arm

.github/workflows/poc-storage.yml, storage/docker-compose.yml
This commit adds the ability to push container images to GHCR during the
storage container build while running on pull requests. Useful for
testing container images resulting from PRs.
Closes #161
Closes #162
=> build: Push storage container on PRs

integration/README.md, integration/docker-compose.otel.yml, integration/docker-compose.pxe.yml, integration/gateway/Dockerfile, integration/gateway/Dockerfile.storage, integration/xpu-cpu/Dockerfile.telegraf
* Specify public cr to use for public images
* Use SELinux :z on prometheus volume
* Can use pip installed version of docker-compose
=> Fixes for Red Hat environments

.github/workflows/poc-storage-skip.yml
The job names of the storage-poc changed, but we neglected to update it
in the skip job. This commit fixes that.
=> storage-skip: Match job name

integration/README.md, integration/scripts/integration.sh
This is a workaround for issue
https://github.com/opiproject/opi-poc/issues/207
Setting BUILD_SPDK to any value will cause it to build spdk-target
service after the pull when doing integration.sh start
=> Workaround for spdk illegal instruction

integration/docker-compose.pxe.yml, integration/docker-compose.xpu.yml
Without SELinux tags on the volume mounts, strongswan exits with rc 64
when running with SELinux Enforcing
Also adding a tag for pxe that was missed previously.
=> Support SELinux volume mounts for strongswan

integration/README.md, integration/docker-compose.xpu.yml
docker-compose makes little in the way of guarantees for start up time
dependencies.  If one container needs another to be running, it must
be tolerant of that container's start up time.
* Add loops to retry example tests
* Add podman-plugins as required for podman environments
=> Make example clients tolerant of startup times

storage/Dockerfile
'native' arch will cause gcc to optimize using the latest available
instructions on the build CPU.  If the build CPU is newer than the
runtime CPU, it will fail with "Illegal instruction".  'skylake' is
new enough to support the minimum ISA required by spdk/dpdk but old
enough to be largely available.
=> storage: ARCH=skylake to avoid using too new ISA

security/docker-compose.yml
Sometimes, the vpn-client container fails to start with the following
message:
```
ERROR: for vpn-client  Cannot start service vpn-client: Address already in use
```
The Dockerfile for the strongSwan image we are using exposes ports [1].
It's unclear why this conflicts, but my theory is that we are running
`charon` at start which will bind to those ports, and if that happens
before the client starts, the docker daemon will not start the
vpn-client container.
This moves the vpn-client container to start before the strongswan
container to resolve this issue.
Fixes #252
[1] https://github.com/strongX509/docker/blob/master/strongswan/Dockerfile#L36
=> security: Change startup order

storage/Dockerfile, storage/client/Dockerfile, storage/scripts/poc.sh, storage/scripts/x86v.sh, storage/server/Dockerfile
DPDK requires a minimum x86 arch level that includes sse4.2.  gcc
provides a set of generic x86-64-v levels for different architecture
versions.  Version 2 is the minimum that meets the requirements for
DPDK.
* Set x86-64-v2 for spdk container
* Print actual x86-64-v level
* Specify cr to use for golang containers for podman
=> Storage: Use generic x86-64-v2

security/client/ipsec.go, security/docker-compose.yml, security/server/ipsec.go, security/server/ipsec_vici.go
This commit gets initiate and terminate working.
Related to #220
```
vagrant@bullseye:/git/opi-poc/security$ docker logs security-opi-security-server-1
2022/08/18 19:47:06 server listening at [::]:50151
2022/08/18 19:47:07 IPsecLoadConn: Received: name:"opi-test" version:"2" local_addrs:{addr:"192.168.200.200"} remote_addrs:{addr:"192.168.200.210"} proposals:{crypto_alg:AES256GCM128 integ_alg:SHA256_96 dhgroups:CURVE25519} vips:{vip:"0.0.0.0"} local_auth:{auth:PSK id:"hacker@strongswan.org"} remote_auth:{auth:PSK id:"server.strongswan.org"} children:{name:"opi-child" esp_proposals:{crypto_alg:AES256GCM128 integ_alg:SHA512 dhgroups:CURVE25519} remote_ts:{ts:{cidr:"10.1.0.0/16"}}}
2022/08/18 19:47:07 DUMPING conn.Local: {psk [] hacker@strongswan.org    []}
2022/08/18 19:47:07 DUMPING …
```
=> security: Connection up and down

security/client/ipsec.go, security/server/ipsec.go, security/server/ipsec_vici.go
This implements the IPsecVersion API, which acquires version information
from the daemon underneath and returns it in the IPsecVersionResp
structure.
Related to #320
=> security: Implement IPsecVersion API

security/client/go.mod, security/client/go.sum, security/client/ipsec.go, security/server/go.mod, security/server/go.sum, security/server/ipsec.go, security/server/ipsec_vici.go, security/server/ipsec_vici_parse.go
This implements the final two OPI Security IPsec APIs:
* IPsecListConns()
* IPsecListCerts()
With these now implemented, all of the APIs are now shown here, and are
tested in the CI, as the client calls them all. Should be a good example
for vendors to look at.
Related to #320
=> security: Finish implementing APIs

storage/client/frontend.go, storage/client/go.mod, storage/client/go.sum, storage/server/frontend.go, storage/server/go.mod, storage/server/go.sum
Opi-api has id's removed from Subsystem api's. Also SubsystemCreateResponse now contains uuid. So updating storage poc to be in sync.
Signed-off-by: Amar Vishwakarma <amarv@marvell.com>
Signed-off-by: Michal Kalderon <mkalderon@marvell.com>
=> Issue#337: Fixing storage poc wrt nqn/id related changes

storage/client/frontend.go, storage/server/backend.go, storage/server/frontend.go
Fixes #367
tested like this
```
$ docker run --network=storage_opi --rm -it namely/grpc-cli call opi-spdk-server:50051 NVMeSubsystemGet ""
connecting to opi-spdk-server:50051
Rpc failed with status code 2, error message: bdev_get_bdevs: json response error: No such device
```
server is no longer crashing , see:
```
opi-spdk-server_1  | 2022/09/21 20:12:01 NVMeSubsystemGet: Received from client:
opi-spdk-server_1  | 2022/09/21 20:12:01 Sending to SPDK: {"jsonrpc":"2.0","id":24,"method":"bdev_get_bdevs","params":{"name":"OpiMalloc"}}
opi-spdk-server_1  | 2022/09/21 20:12:01 Received from SPDK: {24 {-19 No such device} 0xc0003ac348}
opi-spdk-server_1  | 2022/09/21 20:12:01 error: bdev_get_bdevs: json response error: No such device
```
=> storage: return RPC error on call() error

integration/docker-compose.xpu.yml
=> bump strongswan docker image to 5.9.7

storage/spdk/Dockerfile
`Note that --without-isal is no longer supported as a configure option.` see https://github.com/spdk/spdk/commit/dd2c08d2d19b00c3e5674863632f12d45831758d
=> SPDK: bump release to 22.09 (sept)

.github/workflows/linters.yml
Disable go linter on security directories as it currently breaks the build.
I intend to re-enable the linter and fix the lint issues but I don't have availability to do it now.
Signed-off-by: patrick-alessi <patrick.alessi@dell.com>
=> Disable go linter on security directories

integration/README.md, integration/scripts/integration.sh
Now that the spdk image uses a target to avoid requiring avx512, the workaround is no longer needed.
=> Remove old spdk avx512 workaround

integration/docker-compose.xpu.yml
From: integration_xpu-spdk-web_1
Error details: Invalid or non-existing address: '/var/tmp/spdk.sock'
=> integration: fix /var/tmp mount in xpu

integration/docker-compose.pxe.yml
When changing the base image from a full python image to a slim python image, the curl based healthcheck no longer worked.  Replace it with a simple inline python program.
Fixes #471 
=> integration: fix web healthcheck

integration/docker-compose.pxe.yml, integration/docker-compose.spdk.yml, integration/docker-compose.xpu.yml
Renovate bot needs both tag and digest to work properly
Investigated renovate log/console and saw errors
This is fixing 86329b5012e27a56411ce8199ec13bec30de9214
=> [docker] pull images by tag AND digest instead of labels

lab/hardware/A100G/arista.config
- device name
- dhcp on mgmt
- shuts down 100G interface to ToR (was creating problems, test traffic was reaching the tor)
=> enables dhcp on management interface
